### ISSUE TITLE
How to enable access logs for gRPC server

### ISSUE THREAD

**Issue by JaganathJoshua** [LogNet/grpc-spring-boot-starter#110]
Hi,
I'm using grpc-spring-boot-starter for my grpc spring boot application. I'm trying to enable access logs for my grpc server. I'm trying to use the latest changes related to access logs in reactor-netty (https://github.com/reactor/reactor-netty/commit/e26831e0ee567f39313fb9741bb761e145cb298e) I guess grpc-spring-boot-starter is not using reactor-netty HttpServer, is a way where i can configure reactor-netty HttpServer or any other ways to get access logs at grpc server side.

**Comment by jvmlet** [comment]
You can run embedded grpc server together with embedded tomcat/any other embedded server side by side in the same boot app. Just add appropriate boot starter to your app.
* I would suggest  to use ELK stack for log access

**Comment by JaganathJoshua** [comment]
ELK helps to aggregate the logs. But what I'm looking for is to configure "access logs" for grpc server. This support is there in reactor-netty HttpServer. Is it possible to use this server in grpc-spring-boot-starter, right now its using embedded NettyServer

**Comment by jvmlet** [comment]
As  I mentioned, you can run (add any other starter as dependency) whatever server together with embedded grpc server provided by this starter.

**Comment by drorventura** [comment]
Maybe it's not relevant anymore since my reply is 2 months from your post but a simple solution you could do in that case is to define a global interceptor that will log the rpc entry which will work the same as an access log.
Each request received to any rpc you define will visit that interceptor. 
Note that logging or any other side effect comes with a penalty, most of the time affordable but just keep in mind, maybe wrap that in a feature flag. 

I assume that if you chose gRPC then you plan to work in a distributed system environment, probably in a microservice architecture. 
Or you need some http2 features in your application. 
In case not you should ask yourself why choosing gRPC and not use Spring's strength with what it allows using REST out of the box, also using protobuf. 

Don't get me wrong I'm using gRPC at the moment and i like it but it brings to the table some overhead and infrastructure challenges that needs to be taken into consideration. 

But if you are building a microservice architecture, and you want to apply network handling such as monitoring, logging, tracing, discovery, rate limiting, circuit breaking and so on then, the best way to handle it in my opinion, depends on how big is your microservice stack and in case you are working in a docker environment is to use a service mesh solution. 

I won't start with that from the start but the idea of Decoupling between network and business logic is a good practice. 
There are many good open source product that hanfles the networking challenges very well. Envoy is one of them

Good luck

**Comment by jvmlet** [comment]
@JaganathJoshua , you can use `serverBuilder.setBinaryLog(new BinaryLogProviderImpl(...))` inside your custom server builder configurer. To register your custom configurer see [this](https://github.com/LogNet/grpc-spring-boot-starter#43-custom-grpc-server-configuration)

[Here](https://github.com/grpc/grpc-java/blob/master/services/src/test/java/io/grpc/services/BinaryLogProviderImplTest.java) are the usage samples

**Comment by drorventura** [comment]
> @JaganathJoshua , you can use `serverBuilder.setBinaryLog(new BinaryLogProviderImpl(...))` inside your custom server builder configurer. To register your custom configurer see [this](https://github.com/LogNet/grpc-spring-boot-starter#43-custom-grpc-server-configuration)
> 
> [Here](https://github.com/grpc/grpc-java/blob/master/services/src/test/java/io/grpc/services/BinaryLogProviderImplTest.java) are the usage samples


I wasn't aware of the binaty log spec so thanks :)
but it's not yet available to be used yet (not supported).
From the java io.grpc core 1.19.0 implementation:
```
  /**
   * Sets the BinaryLog object that this server should log to. The server does not take
   * ownership of the object, and users are responsible for calling {@link BinaryLog#close()}.
   *
   * @param binaryLog the object to provide logging.
   * @return this
   * @since 1.13.0
   */
  @ExperimentalApi("https://github.com/grpc/grpc-java/issues/4017")
  public T setBinaryLog(BinaryLog binaryLog) {
    throw new UnsupportedOperationException();
  }
```

**Comment by jvmlet** [comment]
See `io.grpc.internal.AbstractServerImplBuilder`

**Comment by chsi13** [comment]
@drorventura did you enable debug logging through binary log api ? Do you have any samples ? thx
