### ISSUE TITLE
The spring notation @ComponentScan does not let the gRPC server start

### ISSUE THREAD

**Issue by luigi-riefolo** [LogNet/grpc-spring-boot-starter#124]
Hi, I'm trying to user the `@ComponentScan` notation, but it seems that by declaring in `Application.java` the gRPC server does not start and this is the last log line:

```
INFO 2312 --- [           main] com.app.Application                     : Started Application in 4.036 seconds (JVM running for 4.622)
```

while this is the last one printed when working correctly:

```
INFO 3709 --- [           main] o.l.springboot.grpc.GRpcServerRunner     : gRPC Server started, listening on port 10080.
```

The `@ComponentScan` notation is needed to export a repository and auto-wire it in a different project.

Does anyone know why this is happening? Let me know if you need more details.

**Comment by jvmlet** [comment]
If you run your app with debug=true you will see that grpc server is not started because there is no grpc service beans in your app context. This is because you've overwritten the base package discovery of your app  to be different and it doesn't contain your service beans. You will need to add component scan the  way that doesn't prevent your grpc service beans to dissappear.

**Comment by luigi-riefolo** [comment]
@jvmlet thanks for the info, but could you please elaborate a bit on 

> You will need to add component scan the way that doesn't prevent your grpc service beans to dissappear.

I've tried to use different orders, but didn't work, running out of ideas.

**Comment by jvmlet** [comment]
Please post your app annotations and configurations classes under your main
package
