### ISSUE TITLE
Update to proto 3.0.0

### ISSUE THREAD

**Issue by extensia** [LogNet/grpc-spring-boot-starter#19]
First, thanks for your efforts to develop gRPC support for Spring Boot. We are using both frameworks and  think it is a good combination.

Are there any known issues running against the latest gRPC build? I see that protobuf 3.0.0 is now out and that there have been some recent dependency updates in the gRPC repository.

We plan on using grpc-spring-boot-starter with Gradle and are interested about your future plans. As we move forward we are happy to submit pull requests for any issues or improvements.

Best Regards,
David

**Comment by butterklopsi** [comment]
Hi David,
the grpc-spring-boot-starter uses the interface generated by the proto compiler / the static(?) `bindService` for each rpc-service. since some beta versions of proto they started to mark this interface as deprecated and introduced an abstract class that comes with a default implementation for each rpc-function that just returns "onError" with the message "NOT YET IMPLEMENTED". In proto 3.0.0 the old version with the interface is disabled by default, if i now generate my code by proto 3.0.0 and extend the abstract class instead implementing the interface the grpc-spring-boot-starter did not start my grpc service. there is an IllegalArgumentException: `Failed to find 'bindService' method`. It would be very cool if you could update the grpc-spring-boot-starter to work with the abstract class instead of the interface.

thanks
Børge.

**Comment by jvmlet** [comment]
Hi 
Please use the latest build (0.0.4), it supports  protobuf 3.0.0
