### ISSUE TITLE
GRpcExceptionHandler doesn't work [Kotlin]

### ISSUE THREAD

**Issue by TheHett** [LogNet/grpc-spring-boot-starter#268]
Hi, thanks for the work you've done. It's really great starter!

I have some trouble, maybe it related with Kotlin CoroutineImpl. 
The interceptor below does not catch exception:

```
@GRpcService
class TempUrlService() : TempUrlServiceGrpcKt.TempUrlServiceCoroutineImplBase() {

    private val logger = KotlinLogging.logger {}

    @GRpcExceptionHandler
    fun anotherHandler(e: NullPointerException, scope: GRpcExceptionScope): Status {
        logger.warn { "NPE!" }
        return Status.INTERNAL
    }

    @Throws(Throwable::class)
    override suspend fun createThumbnailTempUrl(request: ThumbRequest): ThumbResponse {
        throw NullPointerException("HELLO")
    }
}
```

Using  4.5.10 version.

**Comment by jvmlet** [comment]
Can you please try  to debug to see the private handler resolvers discovered [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/d70346be2035131b41997594657776c7619427dc/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerMethodResolver.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L42) for your `TempUrlService` service bean ?

**Comment by TheHett** [comment]
@jvmlet 
My handler are presented, but method `resolveMethodByThrowable` isn't invoked.
I could not find the entry point where interceptor should be invoked.

**Comment by jvmlet** [comment]
for unary call it's called from [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/d70346be2035131b41997594657776c7619427dc/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerInterceptor.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L89)

**Comment by jvmlet** [comment]
Ohh, I think the issue is [this ](https://github.com/LogNet/grpc-spring-boot-starter/blob/d70346be2035131b41997594657776c7619427dc/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerMethodResolver.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) line , I should also check the  `privateResolvers`

**Comment by jvmlet** [comment]
Meanwhile, please add dummy global handler as temporary workaround ..

**Comment by TheHett** [comment]
Hi, do you mean `GRpcServiceAdvice` or `GRpcGlobalInterceptor` ?

First doesn't work too for me

![image](https://user-images.githubusercontent.com/946246/145777898-aaef97b5-faf5-4647-8543-b42f3e9d9f48.png)

While I wrapped in try..catch :)

**Comment by jvmlet** [comment]
The problem is [this line ](https://github.com/LogNet/grpc-spring-boot-starter/blob/d70346be2035131b41997594657776c7619427dc/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerMethodResolver.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46), it should check private resolvers as well. So, meanwhile, you can workaround the bug by adding dummy `@GRpcServiceAdvice` with `@GRpcServiceAdvice` method, it will force  interceptor to proceed ([here](https://github.com/LogNet/grpc-spring-boot-starter/blob/d70346be2035131b41997594657776c7619427dc/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerInterceptor.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L34)) and you private handler should be invoked

**Comment by TheHett** [comment]
Hmmm, I suspected that the problem is in the coroutines, but not. This doesn't work too:

```kotlin
@GRpcService()
class FileService() : FileServiceGrpc.FileServiceImplBase() {
    private val logger = KotlinLogging.logger {}
    override fun getInfo(request: FileInfoRequest, responseObserver: StreamObserver<FileInfoResponse>) {
        throw TestException("Hello")
    }
}
```

**Comment by jvmlet** [comment]
You should have both `@GRpcExceptionHandler` : global and private. Your private handler will be called

**Comment by jvmlet** [comment]
You also should wrap your exception with `throw new GRpcRuntimeExceptionWrapper(new TestException(),"myHint")`, the `RuntimeException` is caught...

**Comment by TheHett** [comment]
Bing, runtime exception is works!
The problem is that the Kotlin does not have `throws` signature and not differs checked/non-checked exceptions. In may case I testing java checked exception. 

If declared next exception, no any logs will produced on error and it big problem:
```kotlin
class TestException(message: String) : java.lang.Exception(message)
```

Next code works with runtime exception (global handler registered too):
```kotlin
@GRpcService()
class FileService() : FileServiceGrpc.FileServiceImplBase() {

    @GRpcExceptionHandler
    fun anotherHandler(e: TestException, scope: GRpcExceptionScope): Status {
        logger.warn { "NPE!" }
        return Status.INTERNAL
    }
    override fun getInfo(request: FileInfoRequest, responseObserver: StreamObserver<FileInfoResponse>) {
        throw TestException("Hello")
    }
}
```

But if trying to extend kotlin corutine impl, again in the logs silence:

```kotlin
@GRpcService()
class FileService() : FileServiceGrpcKt.FileServiceCoroutineImplBase() {
    @GRpcExceptionHandler
    fun anotherHandler(e: TestException, scope: GRpcExceptionScope): Status {
        logger.warn { "NPE!" }
        return Status.INTERNAL
    }
    override suspend fun getInfo(request: FileInfoRequest): FileInfoResponse {
        throw TestException("Hello")
    }
}
````
I suspect that it is different troubles.

**Comment by TheHett** [comment]
I created demo project which reproduces the problems https://github.com/TheHett/grpc_demo/tree/master/src/main/kotlin/com/example/demo/grpc

It should be call manually because I doesn't know how to write test for this
```
grpc_cli call 127.0.0.1:6565  demo.api.DemoService/test ""
```

**Comment by jvmlet** [comment]
You can have a look at demo module in this repo to get the idea how to develop unit tests

**Comment by YannPerthuis** [comment]
Any idea @jvmlet please ?

**Comment by littleniannian** [comment]
i have the same problem with kotlin， @GrpcExceptionHandler in service or @GRpcServiceAdvice on single class doesn't work

**Comment by vicmosin** [comment]
Still relevant with 4.9.1, any updates here?

**Comment by jvmlet** [comment]
Please try with latest `5.1.5-SNAPSHOT`

**Comment by jvmlet** [comment]
`5.1.5` was released

**Comment by vicmosin** [comment]
I am still getting it in `5.1.5`

Maybe it's somehow interfere with the order of interceptors?

```
grpc.security.auth.interceptor-order=-4
grpc.recovery.interceptor-order=-2
grpc.validation.interceptor-order=-1
```
